export const metadata = {
  title: 'To-do app',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, params }) {
  return (
    <html lang="en" data-theme="night">
      <body>
        {children}
      </body>
    </html>
  )
}
